# Site settings
course_name: "BIOS 208: Geometry for Biologists"
course_description: ""
course_semester: "Summer 2023"

baseurl: '/class_summer_2023' #"/BIOS 208" # the subpath of your site, e.g. /blog/
url: "http://stanfordgeombio.github.io/" # the base hostname & protocol for your site

schoolname: "Stanford University"
schoolurl: "https://www.stanford.edu"
#twitter_username: username

#address: |
#    School of Witchcraft and Wizardry
#    Hogwarts
#    Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X
# google_analytics: G-16WVC7K0TB

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
